/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package improgram;

import javax.swing.JOptionPane;

/**
 *
 * @author Joseph Ahrens
 */
public class EditBuddyListDialog extends javax.swing.JDialog {
    boolean backButtonClicked;
    /**
     * Creates new form EditBuddyListDialog
     */
    public EditBuddyListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBuddyListLabel = new javax.swing.JLabel();
        enterBuddyNameLabel = new javax.swing.JLabel();
        chooseBuddyLabel = new javax.swing.JLabel();
        enterBuddyNameField = new javax.swing.JTextField();
        chooseBuddyComboBox = new javax.swing.JComboBox();
        addBuddyButton = new javax.swing.JButton();
        removeBuddyButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editBuddyListLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editBuddyListLabel.setText("Edit Buddy List");

        enterBuddyNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterBuddyNameLabel.setText("Enter Buddy Name:");

        chooseBuddyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chooseBuddyLabel.setText("Choose Buddy:");

        enterBuddyNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enterBuddyNameField.setText("Enter Buddy Name");

        chooseBuddyComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chooseBuddyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addBuddyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBuddyButton.setText("Add Buddy");
        addBuddyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBuddyButtonActionPerformed(evt);
            }
        });

        removeBuddyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeBuddyButton.setText("Remove Buddy");
        removeBuddyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBuddyButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseBuddyLabel)
                            .addComponent(enterBuddyNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseBuddyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(removeBuddyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterBuddyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(addBuddyButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(18, 18, 18)
                                .addComponent(closeButton))
                            .addComponent(editBuddyListLabel))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBuddyListLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBuddyNameLabel)
                    .addComponent(enterBuddyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBuddyButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseBuddyLabel)
                    .addComponent(chooseBuddyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBuddyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBuddyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBuddyButtonActionPerformed
        JOptionPane.showMessageDialog(this, "The system will look for a buddy with the name that was entered in the username field and add it if it exists, and tell the user if it was successfully added or not.");
    }//GEN-LAST:event_addBuddyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backButtonClicked = true;
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeBuddyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBuddyButtonActionPerformed
        JOptionPane.showMessageDialog(this, "The system will tell the user if the buddy was successfully removed from the user's buddy list.");
    }//GEN-LAST:event_removeBuddyButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBuddyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox chooseBuddyComboBox;
    private javax.swing.JLabel chooseBuddyLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel editBuddyListLabel;
    private javax.swing.JTextField enterBuddyNameField;
    private javax.swing.JLabel enterBuddyNameLabel;
    private javax.swing.JButton removeBuddyButton;
    // End of variables declaration//GEN-END:variables
}
