/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package improgram;

import java.awt.Frame;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph Ahrens
 */
public class EditBuddyListDialog extends javax.swing.JDialog {
    ServerCommunicator server;
    Frame parent;
    DefaultComboBoxModel box;
    /**
     * Creates new form EditBuddyListDialog
     */
    public EditBuddyListDialog(java.awt.Frame parent, boolean modal, ServerCommunicator server) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.server = server;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBuddyListLabel = new javax.swing.JLabel();
        enterBuddyNameLabel = new javax.swing.JLabel();
        chooseBuddyLabel = new javax.swing.JLabel();
        enterBuddyNameField = new javax.swing.JTextField();
        chooseBuddyComboBox = new javax.swing.JComboBox();
        addBuddyButton = new javax.swing.JButton();
        removeBuddyButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editBuddyListLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editBuddyListLabel.setText("Edit Buddy List");

        enterBuddyNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterBuddyNameLabel.setText("Enter Buddy Name:");

        chooseBuddyLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chooseBuddyLabel.setText("Choose Buddy:");

        enterBuddyNameField.setColumns(12);
        enterBuddyNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        box = new DefaultComboBoxModel();
        updateChooseBuddyComboBox();
        chooseBuddyComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateChooseBuddyComboBox();
        chooseBuddyComboBox.setModel(box);

        addBuddyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBuddyButton.setText("Add Buddy");
        addBuddyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBuddyButtonActionPerformed(evt);
            }
        });

        removeBuddyButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeBuddyButton.setText("Remove Buddy");
        removeBuddyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBuddyButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseBuddyLabel)
                            .addComponent(enterBuddyNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseBuddyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeBuddyButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterBuddyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(addBuddyButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(editBuddyListLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(refreshButton)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBuddyListLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterBuddyNameLabel)
                    .addComponent(enterBuddyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBuddyButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseBuddyLabel)
                    .addComponent(chooseBuddyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBuddyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Edit Buddy List - Instant Messaging Program");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBuddyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBuddyButtonActionPerformed
        int response = server.addBuddy(server.getCurrentUser(), enterBuddyNameField.getText());
        if(response == 106){ 
            server.buddies.add(enterBuddyNameField.getText());
            JOptionPane.showMessageDialog(rootPane, "Added " + enterBuddyNameField.getText() + " to the buddy list.");
            updateChooseBuddyComboBox();
            
        }
        else if(response == 111){
            JOptionPane.showMessageDialog(rootPane, "Error " + response + " - Could not add " + enterBuddyNameField.getText() + " to buddy list.");
        }
        else if(response == 112){
            JOptionPane.showMessageDialog(rootPane, "Error " + response + " - " + enterBuddyNameField.getText() + " does not exist.");
        }
        else if(response == 113){
            JOptionPane.showMessageDialog(rootPane, "Error " + response + " - Can't add yourself to your buddy list!");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Did not recieve error/message code.");
        }
    }//GEN-LAST:event_addBuddyButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        MainWindowDialog mainWindow = new MainWindowDialog(parent, true, server);
        mainWindow.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        mainWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeBuddyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBuddyButtonActionPerformed
        String buddy = chooseBuddyComboBox.getSelectedItem().toString();
        int response = server.removeBuddy(server.getCurrentUser(), buddy);
        if(response == 107){
            server.buddies.remove(buddy);
            JOptionPane.showMessageDialog(rootPane, "Removed " + buddy + " from the buddy list.");
            updateChooseBuddyComboBox();
        }
        else if(response == 112){
            JOptionPane.showMessageDialog(rootPane, "Error " + response + " - Could not remove " + buddy + " from buddy list.");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Did not recieve error/message code.");
        }
    }//GEN-LAST:event_removeBuddyButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateChooseBuddyComboBox();
    }//GEN-LAST:event_refreshButtonActionPerformed
    
    public void updateChooseBuddyComboBox(){
        box.removeAllElements();
        for(int i = 0; i < server.buddies.size(); i++){
            box.addElement(server.buddies.get(i));
            System.out.println("Added " + server.buddies.get(i) + " to the list / box.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBuddyButton;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox chooseBuddyComboBox;
    private javax.swing.JLabel chooseBuddyLabel;
    private javax.swing.JLabel editBuddyListLabel;
    private javax.swing.JTextField enterBuddyNameField;
    private javax.swing.JLabel enterBuddyNameLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton removeBuddyButton;
    // End of variables declaration//GEN-END:variables
}
