/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package improgram;

import javax.swing.JOptionPane;

/**
 *
 * @author Joseph Ahrens
 */
public class MainWindowDialog extends javax.swing.JDialog {
    boolean editBuddyListMenuItemClicked, messagesMenuItemClicked, logOutButtonClicked;
    /**
     * Creates new form MainWindowDialog
     */
    public MainWindowDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buddiesOnlineLabel = new javax.swing.JLabel();
        unreadMessagesLabel = new javax.swing.JLabel();
        buddiesOnlineComboBox = new javax.swing.JComboBox();
        logOutButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        buddiesMenu = new javax.swing.JMenu();
        editBuddyListMenuItem = new javax.swing.JMenuItem();
        messagesMenu = new javax.swing.JMenu();
        messagesMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buddiesOnlineLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buddiesOnlineLabel.setText("Buddies Online:");

        unreadMessagesLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        unreadMessagesLabel.setText("Unread Messages:");

        buddiesOnlineComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buddiesOnlineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        logOutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buddiesMenu.setText("Buddies");

        editBuddyListMenuItem.setText("Edit Buddy List");
        editBuddyListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBuddyListMenuItemActionPerformed(evt);
            }
        });
        buddiesMenu.add(editBuddyListMenuItem);

        menuBar.add(buddiesMenu);

        messagesMenu.setText("Messages");

        messagesMenuItem.setText("Messages");
        messagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesMenuItemActionPerformed(evt);
            }
        });
        messagesMenu.add(messagesMenuItem);

        menuBar.add(messagesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unreadMessagesLabel)
                    .addComponent(buddiesOnlineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buddiesOnlineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(logOutButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)
                        .addGap(9, 9, 9)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buddiesOnlineLabel)
                    .addComponent(buddiesOnlineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOutButton))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unreadMessagesLabel)
                    .addComponent(closeButton))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBuddyListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBuddyListMenuItemActionPerformed
        editBuddyListMenuItemClicked = true;
        setVisible(false);
    }//GEN-LAST:event_editBuddyListMenuItemActionPerformed

    private void messagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesMenuItemActionPerformed
        messagesMenuItemClicked = true;
        setVisible(false);
    }//GEN-LAST:event_messagesMenuItemActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        JOptionPane.showMessageDialog(this, "You logged out.");
        setVisible(false);
        logOutButtonClicked = true;
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu buddiesMenu;
    private javax.swing.JComboBox buddiesOnlineComboBox;
    private javax.swing.JLabel buddiesOnlineLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JMenuItem editBuddyListMenuItem;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu messagesMenu;
    private javax.swing.JMenuItem messagesMenuItem;
    private javax.swing.JLabel unreadMessagesLabel;
    // End of variables declaration//GEN-END:variables
}
