/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package improgram;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph Ahrens
 */
public class MainWindowDialog extends javax.swing.JDialog {
    ServerCommunicator server;
    Frame parent;
    DefaultListModel list = new DefaultListModel();
    
    /**
     * Creates new form MainWindowDialog
     */
    public MainWindowDialog(java.awt.Frame parent, boolean modal, ServerCommunicator server) {
        super(parent, modal);
        initComponents();
        this.server = server;
        this.parent = parent;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        logOutButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        buddyList = new javax.swing.JList();
        buddyListLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        buddiesMenu = new javax.swing.JMenu();
        editBuddyListMenuItem = new javax.swing.JMenuItem();
        messagesMenu = new javax.swing.JMenu();
        messagesMenuItem = new javax.swing.JMenuItem();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logOutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeButton.setText("Close Program");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        updateChooseBuddyComboBox();
        buddyList.setModel(list);
        jScrollPane1.setViewportView(buddyList);

        buddyListLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        buddyListLabel.setText("Buddies");

        refreshButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        buddiesMenu.setText("Buddies");

        editBuddyListMenuItem.setText("Edit Buddy List");
        editBuddyListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBuddyListMenuItemActionPerformed(evt);
            }
        });
        buddiesMenu.add(editBuddyListMenuItem);

        menuBar.add(buddiesMenu);

        messagesMenu.setText("Messages");

        messagesMenuItem.setText("Messages");
        messagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesMenuItemActionPerformed(evt);
            }
        });
        messagesMenu.add(messagesMenuItem);

        menuBar.add(messagesMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logOutButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshButton)
                                .addGap(18, 18, 18)
                                .addComponent(closeButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(buddyListLabel)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buddyListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutButton)
                    .addComponent(closeButton)
                    .addComponent(refreshButton))
                .addGap(55, 55, 55))
        );

        getAccessibleContext().setAccessibleName("Main Window - Instant Messaging Program");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void editBuddyListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBuddyListMenuItemActionPerformed
        setVisible(false);
        EditBuddyListDialog editBuddies = new EditBuddyListDialog(parent, true, server);
        editBuddies.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        editBuddies.setVisible(true);
    }//GEN-LAST:event_editBuddyListMenuItemActionPerformed

    private void messagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesMenuItemActionPerformed
        setVisible(false);
        MessagesDialog messagesDialog = new MessagesDialog(parent, true, server);
        messagesDialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        messagesDialog.setVisible(true);
    }//GEN-LAST:event_messagesMenuItemActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        int response = server.logOut(server.getCurrentUser());
        if(response == 104){
            JOptionPane.showMessageDialog(rootPane, "You have logged out.");
            setVisible(false);
            server.clearInfo();
            LoginDialog logInDialog = new LoginDialog(parent, true, server);
            logInDialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            logInDialog.setVisible(true);
        }
        else if(response == 105){
            JOptionPane.showMessageDialog(rootPane, server.getCurrentUser() + " is already logged out.");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error - Did not recieve error/message code.");
        }
        
        
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int response = server.logOut(server.getCurrentUser());
        if(response == 104){
            JOptionPane.showMessageDialog(rootPane, "Logged out. Closing program...");
            server.clearInfo();
            System.exit(0);
        }
        else if(response == 105){
            JOptionPane.showMessageDialog(rootPane, server.getCurrentUser() + " is already logged out.");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error - Could not log out.");
        }
        
    }//GEN-LAST:event_closeButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateChooseBuddyComboBox();
    }//GEN-LAST:event_refreshButtonActionPerformed
    
    public void updateChooseBuddyComboBox(){
        list.clear();
        for(int i = 0; i < server.buddies.size(); i++){
            list.addElement(server.buddies.get(i));
            System.out.println("Added " + server.buddies.get(i) + " to the list / box.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu buddiesMenu;
    private javax.swing.JList buddyList;
    private javax.swing.JLabel buddyListLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JMenuItem editBuddyListMenuItem;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu messagesMenu;
    private javax.swing.JMenuItem messagesMenuItem;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
